"""Initial migration with all models including Document

Revision ID: 58e9227db81a
Revises: 
Create Date: 2025-06-17 00:41:35.128076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e9227db81a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if schema_versions table exists before trying to drop it
    try:
        op.drop_table('schema_versions')
    except:
        pass  # Table doesn't exist, which is fine
    
    # Make table operations more robust
    try:
        with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
            try:
                batch_op.drop_index('idx_sessions_topic_id')
            except:
                pass
            try:
                batch_op.drop_index('idx_sessions_user_id')
            except:
                pass
    except:
        pass  # Table doesn't exist

    try:
        with op.batch_alter_table('messages', schema=None) as batch_op:
            batch_op.alter_column('attachment_filename',
                   existing_type=sa.TEXT(),
                   type_=sa.String(length=255),
                   existing_nullable=True)
            batch_op.alter_column('attachment_path',
                   existing_type=sa.TEXT(),
                   type_=sa.String(length=500),
                   existing_nullable=True)
            try:
                batch_op.drop_index('idx_messages_session_id')
            except:
                pass
    except:
        pass  # Table doesn't exist

    try:
        with op.batch_alter_table('topics', schema=None) as batch_op:
            try:
                batch_op.drop_index('idx_topics_created_by')
            except:
                pass
    except:
        pass  # Table doesn't exist

    try:
        with op.batch_alter_table('users', schema=None) as batch_op:
            try:
                batch_op.drop_index('idx_users_email')
            except:
                pass
    except:
        pass  # Table doesn't exist

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.create_index('idx_users_email', ['email'], unique=False)
    except:
        pass

    try:
        with op.batch_alter_table('topics', schema=None) as batch_op:
            batch_op.create_index('idx_topics_created_by', ['created_by'], unique=False)
    except:
        pass

    try:
        with op.batch_alter_table('messages', schema=None) as batch_op:
            batch_op.create_index('idx_messages_session_id', ['session_id'], unique=False)
            batch_op.alter_column('attachment_path',
                   existing_type=sa.String(length=500),
                   type_=sa.TEXT(),
                   existing_nullable=True)
            batch_op.alter_column('attachment_filename',
                   existing_type=sa.String(length=255),
                   type_=sa.TEXT(),
                   existing_nullable=True)
    except:
        pass

    try:
        with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
            batch_op.create_index('idx_sessions_user_id', ['user_id'], unique=False)
            batch_op.create_index('idx_sessions_topic_id', ['topic_id'], unique=False)
    except:
        pass

    try:
        op.create_table('schema_versions',
        sa.Column('version', sa.INTEGER(), nullable=True),
        sa.Column('applied_at', sa.TEXT(), nullable=False),
        sa.Column('description', sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint('version')
        )
    except:
        pass  # Table already exists or can't be created
    # ### end Alembic commands ###
